# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/docs/source/conf.py  # Path to your Sphinx configuration file

python:
  install:
    - method: pip
      path: .
    - requirements: docs/docs/requirements.txt
