# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04  # Required for specifying the OS. Defaults to Ubuntu.
  tools:
    python: "3.9"  # Specify Python version (adjust if necessary)

sphinx:
  configuration: docs/docs/source/conf.py  # Path to your Sphinx configuration file

python:
  install:
    - method: pip
      path: .
    - requirements: docs/docs/requirements.txt
